### ISSUE TITLE
Detaching an output file from event tree

### ISSUE THREAD

**Issue by jgalan** [rest-for-physics/framework#118]
Hi,

I have seen that even if I set "outputEvent" parameter "off", I get the event tree at the output file.

See also discussion at the forum:

https://rest-forum.unizar.es/t/behaviour-of-inputanalysis-inputevent-and-outputevent-in-trestprocessrunner/187

**Comment by nkx111** [comment]
I believe this parameter has been renamed to 'outputEventStorage'. Others are also renamed. This is to prevent the conflict with the datamember "fOutputEvent".

**Comment by jgalan** [comment]
I see
