### ISSUE TITLE
TRestBenchMarkProcess to be recovered from quarantine

### ISSUE THREAD

**Issue by jgalan** [rest-for-physics/framework#12]
This is a pure analysis process. However, traces of TRestRawSignal are found. It should be reviewed to remove those dependencies.

**Comment by nkx111** [comment]
It seems to be a redundant include of TRestRawSignal.h. We can directly remove the line. There is no dependence.

**Comment by jgalan** [comment]
Ok, I just moved it to `framework/analysis`
