### ISSUE TITLE
Some observables are not multithread safe

### ISSUE THREAD

**Issue by cmargalejo** [rest-for-physics/framework#126]
The observable` sAna_MeanRate_InHz` gives different results when the data analysis is performed in multithread mode than when it is done using a single thread. It's true that we found some event ID issues when multithreading and we introduced some warnings that come out during the analysis. So maybe it is related to this.
![image](https://user-images.githubusercontent.com/77193103/152513333-a6ed97f0-3b66-489b-be0c-ae0e4fdb01bf.png)

Not sure if it is possible to force a process to be single-threaded. That observable should probably be defined at a dedicated process, e.g. `TRestRateAnalysisProcess`. There might be other observables affected, as `timeDelay`.

**Comment by jgalan** [comment]
I might have found a quick fix for that, could you re-compile using `mean_rate_fix` branch at rest-for-physics/rawlib#47, and see if the result is thread number dependent?

**Comment by jgalan** [comment]
Hi @cmargalejo could you try now to run the multi-thread and single-thread versions using the `rates` branch from `rawlib` and `framework`? 

From a clean state a way to do that is:

```
./scripts/checkoutBranch rates`
```

Then, implement `TRestEventRateAnalysisProcess` in your RML, and remove the observables from `TRestRawSignalAnalysisProcess`.

**Comment by cmargalejo** [comment]
> Hi @cmargalejo could you try now to run the multi-thread and single-thread versions using the `rates` branch from `rawlib` and `framework`?

Yes, they both give the same results now.
