### ISSUE TITLE
Remove FindROOT.cmake

### ISSUE THREAD

**Issue by lobis** [rest-for-physics/framework#133]
Currently in the repository `/cmake` directory we have some `Find*.cmake` macros that in my opinion should be removed. In particular `FindROOT.cmake`.

when invoking `find_package(ROOT)` cmake macro, it will search for the corresponding macro, first in the project directory. If it doesn't find it there, it will search on some other standard directories and find it (if ROOT is installed and sourced). The problem is that since we have our own `FindROOT.cmake` macro, its overwritting the installation macro. Our macro is probably based on some specific old root version. We should use the current root installation macro.

The fix should be as simple as removing the old macro, however there are some very strange bugs happening (which took my quite a while to relate to this macro...).

In particular when doing the `make` it will fail in the first line giving:
```
/bin/sh: 1: -f: not found
```

I want to get it removed now because I think its causing issues when linking to a newer version of Garfield, throwing errors like:

```
CMake Error at cmake/MacroRootDict.cmake:509 (add_library):
  Target "RestDetector" links to target "ROOT::Geom" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  source/libraries/detector/CMakeLists.txt:30 (COMPILELIB)


CMake Error at cmake/MacroRootDict.cmake:509 (add_library):
  Target "RestDetector" links to target "ROOT::Gdml" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  source/libraries/detector/CMakeLists.txt:30 (COMPILELIB)


CMake Error at cmake/MacroRootDict.cmake:509 (add_library):
  Target "RestDetector" links to target "ROOT::Graf3d" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  source/libraries/detector/CMakeLists.txt:30 (COMPILELIB)


-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.

[Failed to reload]
```

I have no idea what we are doing that is causing the `-f` error, any ideas are welcome.

**Comment by jgalan** [comment]
I dont know, perhaps if that macro is removed there is a CMAKE variable that allows to define where cmake macros can be found?

**Comment by lobis** [comment]
> I dont know, perhaps if that macro is removed there is a CMAKE variable that allows to define where cmake macros can be found?

Yes, this is by default, if we remove the macro CMAKE will find the correct macro. This is working. The problem is that the compilation is not working with the correct macro, for some reason.

**Comment by jgalan** [comment]
And which is the right script at $ROOTSYS?

**Comment by lobis** [comment]
its at `$ROOTSYS/cmake/ROOTConfig.cmake`, [here](https://cmake.org/cmake/help/latest/command/find_package.html) you can find more details.

**Comment by nkx111** [comment]
> /bin/sh: 1: -f: not found

This error is occurred when `rootcint` is not found(variable ${ROOTCINT_EXECUTABLE} is empty), I remember that. We can check if `$ROOTSYS/cmake/ROOTConfig.cmake` sets the proper cmake variable

**Comment by lobis** [comment]
> > /bin/sh: 1: -f: not found
> 
> This error is occurred when `rootcint` is not found(variable ${ROOTCINT_EXECUTABLE} is empty), I remember that. We can check if `$ROOTSYS/cmake/ROOTConfig.cmake` sets this cmake variable properly

Thanks! this fixed the issue, however we may need to implement some conditional logic to define the executable for different platforms (Windows for instance). Maybe there is a multi platform solution using `root-config`, I didn't find it.

**Comment by lobis** [comment]
Merging https://github.com/rest-for-physics/framework/pull/145 would close this issue.
