### ISSUE TITLE
Remove using namespace std from header files

### ISSUE THREAD

**Issue by juanangp** [rest-for-physics/framework#156]
Several instances to `using namespace std` are found in several header files, which is considered bad coding practise:
https://stackoverflow.com/questions/1452721/why-is-using-namespace-std-considered-bad-practice

Here a list of the header files where I have found  `using namespace std` in the code:
```
./source/framework/core/inc/TRestTask.h
./source/framework/tools/inc/TRestStringHelper.h
./source/framework/tools/inc/TRestSystemOfUnits.h
./source/framework/tools/inc/TRestDataBase.h
./source/framework/tools/inc/TRestPhysics.h
./source/framework/tools/inc/TRestReflector.h
./source/framework/tools/inc/TRestStringOutput.h
./source/framework/tools/inc/TRestTools.h
./source/packages/restG4/include/PhysicsList.h
./source/packages/restG4/include/EventAction.h
./source/packages/restG4/include/SteppingAction.h
./source/packages/restG4/include/RunAction.h
./source/packages/restG4/include/PrimaryGeneratorAction.h
```
However the required changes in the code could be larger than these header files, as has been pointed in #124 for [TRestAnalysisPlot.h](https://github.com/rest-for-physics/framework/pull/124/files/96d7bc5f1cc5d6a45dfd2207fbde3fd29adda13d..019fba6d2ac37c90ce24251f736ff53007ab9af1#diff-dedf3dd827aabaea9294a8fa8a8266156b16b575d5a5469a29bacca7a895ec28)

I am willing to give a hand on this issue, but I think we should divide the work because the load can be large.

**Comment by lobis** [comment]
I think its enough that when you work on some file, we try to also remove these kind of things in the same PR. We just need everyone to keep these things in mind!

**Comment by jgalan** [comment]
It could probably achieved quickly by find and replace any `----cout <<` by `---std::cout`?

https://stackoverflow.com/questions/11392478/how-to-replace-a-string-in-multiple-files-in-linux-command-line

**Comment by juanangp** [comment]
In fact we should also replace many others such as `string` `vector` `map` . Also, we should cross check the function args. We should also check if `using namespace std` is defined in the source files, perhaps is missing in the classes which are defined in the header.

On the other hand, I prefer to do these changes in a separate PR rather than in other PR that are not connected with this issue.

**Comment by lobis** [comment]
***restG4*** `using namespace std;` and other minor stuff was fixed on https://github.com/rest-for-physics/restG4/pull/35.
