### ISSUE TITLE
Improve cmake libraries compilation system

### ISSUE THREAD

**Issue by jgalan** [rest-for-physics/framework#17]
Following the forum discussion with @nkx111  at

http://ezpc10.unizar.es/t/put-cmake-commands-to-each-library-cmakelists-in-v2-3/433

It would be interesting to improve the cmake library adding system.

The main `CMakeLists.txt` at `sources/` could just call to `add_subdirectory(library/name)`. Then, any other definitions could be placed at the library `CMakeLists.txt` itself.

It could be even improved to loop on all subdirectories found at `source/libraries` and if `RESTLIB_NAME` was enabled, then add the subdirectory `libraries/name`.

**Comment by jgalan** [comment]
This issue could be in connection with issue #5

**Comment by nkx111** [comment]
Hi, I have update cmake system for the framework and github libraries. The compilation and installation is working for me. For the axion and modellib, I am not familiar and didn't do the modification. Maybe @jgalan can help. I have added a new cmake macro `COMPILELIB()` which requires a list of dependency lib name. We can use it to replace the old `COMPILEDIR()`. As in https://github.com/rest-for-physics/detectorlib/blob/d73730cedccb08bc04314721fff0375426b8c3fa/CMakeLists.txt

**Comment by jgalan** [comment]
Ok I will look forward to update `axion` and `model` libraries. But right now it seems there is a problem at the pipeline.

https://lfna.unizar.es/rest-for-physics/framework/-/jobs/13513

I believe before, adding `REST_G4` compilation flag would force `RESTLIB_GEANT4` to be enabled by default.

**Comment by jgalan** [comment]
The build is still failing. It seems that `connectorlib` is not being added. Before, when `detectorlib` and `rawlib` were both enabled, the `connectorlib` would be added automatically.

**Comment by nkx111** [comment]
But TRestRawSignalToSignalProcess shouldn't be there! Do we pull the submodules?

**Comment by nkx111** [comment]
I see there are changes in the code of `rawlib` submodule in the pipeline runner that prevents updating. However the python script to pull submodules still reports success. https://lfna.unizar.es/rest-for-physics/framework/-/jobs/13725

I have updated the script to solve the problem.

**Comment by jgalan** [comment]
Ok, great, just now, when I use `python3 pull-submodules.py --private` I get the following error:

```
projects/iaxo-simulations[ OK ] (946a184)
projects/iaxo-geometry[ OK ] (c47942c)
projects/iaxo-readouts[ OK ] (793c916)
projects/iaxo-simulations/geometry[ OK ] (e676d83)
projects/iaxo-simulations/readouts[ Failed ]
```

It is strange, `projects/iaxo-simulations/geometry` is in itself a submodule, but `projects/iaxo-simulations/readouts` does not exist at all.

I am puzzled here.
