### ISSUE TITLE
Implementation of a generic TRestEventSelectionProcess

### ISSUE THREAD

**Issue by jgalan** [rest-for-physics/framework#18]
It might happen that we process a ROOT file once using a very quick/preliminary analysis. Then, we want to apply a more sophisticated analysis to events that satisfy certain conditions in the resulting file at the analysisTree, even at a late processing stage. In the second more sophisticated and computationally expensive processing chain we may add processes that require more computation. In other words, we will re-process with more detail but for a fewer amount of events.

Thus we need a process that accepts in its definition a list of event ids, or a range of event ids. The case could be extended to other basic event identifiers, as sub-event id, or event Tag, timestamp, ... The process in each event loop will compare the event ID against the ones that are in the list. If the ID is not found inside the list it will just return `return NULL`.

This process could be as simple as just retrieving the event list from a text file, a ROOT TTree, or directly at the RML.

Or, it could become more complex and receive as input the ROOT file containing the `analysisTree`, and define the selection rules that will generate the event ID list inside the `InitProcess`.

**Comment by DavidDiezIb** [comment]
Now EventSelectionProcess allows to read ID selection from txt file or select them from root file given conditions over the observables.
Forgot to label the commit: 78ef9446912c40ca891a76e56c62c9734cae202b

**Comment by jgalan** [comment]
Perfect. Do you see a way to enter a validation test in the pipeline? This could be done at the `restManager_process` stage.

A possibility would be that the stage runs after `01_NLDBD` pipeline job. And therefore, the file `${CI_PROJECT_DIR}/install/examples/01.NLDBD/Run00001_NLDBD_Test.root` should be already available for that stage.

You could then just place on the pipeline directory a new folder named `selection`, with two RMLs, one with `g4Ana.rml` and other one implementing your process and receiving as input the file generated by the process and some rule.

```
restManager --c g4Analysis.rml --f ${CI_PROJECT_DIR}/install/examples/01.NLDBD/Run00001_NLDBD_Test.root
restManager --c g4OnSelection.rml --f ${CI_PROJECT_DIR}/install/examples/01.NLDBD/Run00001_NLDBD_Test.root
Validate.C("selection_output.root")
```

where `g4OnSelection.rml` includes your process with a given rule on the observables. For example "XXenergy >2.4MeV". 


Then, `Validate.C` could just check the number of entries at the final tree, and return 0 if it corresponds with the value you expect.

**Comment by jgalan** [comment]
I believe this process has already been integrated, so probably we could close it.

**Comment by DavidDiezIb** [comment]
I agree, we could close the issue.
