### ISSUE TITLE
Adding compression and splitting option to output file

### ISSUE THREAD

**Issue by nkx111** [rest-for-physics/framework#190]
It is interesting to implement compression and auto splitting for process output files. Sometimes the file size becomes too large in large dataset. If it exceeds 100GB I believe there will be problems due to the default TTree size. By either doing file compression and auto splitting we can fix this problem. I have written some code and tested that the auto splitting is working.

1. If file size is small, every thing is normal
2. If it exceeds the limit(set by rml), REST will create extra file series. The splitted files are named as XXX.root.1, XXX.root.2, etc.(with main file named XXX.root). The metadata is still stored in the main file. The splitted files only store analysis tree and event tree object.
3. When opening with TRestRun, if there is extra files series for the input file, It will automatically convert EventTree as TChain. For AnalysisTree, we link additional TChain object, and replace methods like Draw(), Scan(), GetEntries(), etc. to those from TChain.

![image](https://user-images.githubusercontent.com/14999274/166233165-51b8d413-a7d1-4c0d-b059-50300d5d24ed.png)
![image](https://user-images.githubusercontent.com/14999274/166232720-605b9c5b-372c-4d59-8627-ac73528ba7e8.png)

**Comment by jgalan** [comment]
Looks nice! I would then add bytes units to `TRestSystemOfUnits` such as `Mb,kb,Gb,Tb`.
