### ISSUE TITLE
Modify thisREST.cmake to restore previous alias macro functionality

### ISSUE THREAD

**Issue by lobis** [rest-for-physics/framework#21]
Previous to version 2.3 all macros were stored inside the `/macros` directory and were transformed into aliases via

```
foreach(mac ${rest_macros})

string(REPLACE " " "" mac ${mac})
string(REPLACE "rest" "" m ${mac})
```
in the `thisREST.cmake` file.

However since in the new version the modules such as `restG4` are split into submodules (different git respositories), this macro cannot obtain the name of the macros in order to put them into aliases (such as `restViewG4Event` now should be `restManager REST_Geant4_ViewEvent`).

One solution would be to hardcode the aliases into the `thisREST.cmake` file but perhaps there is a more elegant solution that won't break once the macro names change again.

**Comment by jgalan** [comment]
Yes, I guess this can be integrated inside `thisREST.sh`.

We could perhaps create a new cmake macro/function `ADD_REST_MACROS` that does at the same time define the installation target, and fill a PARENT_SCOPE variable with a list containing the name of all `REST_XX_Macro.C` files.

The macro could be something like
```
MACRO( ADD_REST_MACROS /source/path/to/macros targetDirectory )
 install(DIRECTORY /source/path/to/macros
       DESTINATION ./macros/targetDirectory
       COMPONENT install
    )

/// Then we add the macros using glob at  /source/path/to/macros and add them to a global list

ENDMACRO( ADD_REST_MACROS)
```

Then, at the libraries, or packages we would just call this macro. For example, if we are at the /source/libraries/geant4/ directory something similar to that should work

```
ADD_REST_MACROS( ./macros geant4 )
```

**Comment by nkx111** [comment]
Sometimes we don't want all our macros files to be executed as alias with `restXXX`. I suggest we still add them manually, and follow the old logic: `restXXX = restManager XXX`. In this case, we just need to add lines in CMakeLists.txt in the submodules like:

```
set(rest_macros ${rest_macros} "restGeant4_ViewEvent")
set(rest_macros ${rest_macros} "restGeant4_ViewGeometry")
set(rest_macros ${rest_macros} PARENT_SCOPE)
```

**Comment by nkx111** [comment]
I have updated geant4lib to restore `restGean4_ViewEvent` macro

**Comment by jgalan** [comment]
Ok, thanks, I think thats simple enough so that anyone interested can take the initiative to implement a new alias into REST.

I let @lobis to close this issue.
