### ISSUE TITLE
Installation problem with Ubuntu 22.04 (CMake related)

### ISSUE THREAD

**Issue by lobis** [rest-for-physics/framework#236]
I am using a container with Ubuntu 22.04, to reproduce use:

```
docker run -it --rm ghcr.io/lobis/root-geant4-garfield:cpp17_ROOT-v6-26-02_Geant4-v11.0.1_Garfield-9cf89f4c
```

I install REST as usual, only using `restG4` for demonstration:

```
git clone https://github.com/rest-for-physics/framework.git
cd framework
python3 pull-submodules.py --latest
mkdir build && cd build
cmake .. -DCMAKE_INSTALL_PREFIX=/rest/install -DREST_G4=ON
make install
```

Everything seems to work fine but the `restG4` binary is not present in the installation directory, nor is accessible via `restG4` command after loading `thisREST.sh`.

This is probably related to https://github.com/rest-for-physics/framework/pull/200, where the blocking issue was this exact problem, but it was supposedly solved, not sure why its not working now.

It probably isn't directly caused by the version of Ubuntu, but by the version of CMake that comes with Ubuntu 22.04. This does not happen with Ubuntu 20.04, which is the current version used in the pipeline.

**Comment by juanangp** [comment]
This presumably is due to this line https://github.com/rest-for-physics/framework/blob/c5429ece4711ca8d30c4d2f58bcce8def8ca009d/CMakeLists.txt#L23

It seems that the bug still there after `cmake` version `3.21`, because I couldn't check

We can either remove the if or increase the `cmake` version, please check https://cmake.org/cmake/help/latest/policy/CMP0082.html#policy:CMP0082

**Comment by lobis** [comment]
> This presumably is due to this line
> 
> https://github.com/rest-for-physics/framework/blob/c5429ece4711ca8d30c4d2f58bcce8def8ca009d/CMakeLists.txt#L23
> 
> It seems that the bug still there after `cmake` version `3.21`, because I couldn't check
> 
> We can either remove the if or increase the `cmake` version, please check https://cmake.org/cmake/help/latest/policy/CMP0082.html#policy:CMP0082

Thanks!

The cmake version in this case is `3.22.1`.

I think for simplicity its best to remove the `if` entirely, but the best option would be to do the required modifications so that we don't need the `cmake_policy(SET CMP0082 OLD)` line at all.

I will make the required PR.

**Comment by juanangp** [comment]
As pointed in https://github.com/rest-for-physics/framework/issues/162 another solution is to place `add_subdirectory` command after any `install` command in the `CMakeList.txt`.
