### ISSUE TITLE
Dis-ordered event ids when using multi-thread

### ISSUE THREAD

**Issue by nkx111** [rest-for-physics/framework#28]
The event ids will be dis-ordered when we enabled multi-thread. For example, the event id will be 1,3,4,2,5,6,8,7... at entry 1,2,3,4,5,6,7,8. This is because the thread running time for each event is in-predictable. On the other hand, the overall tendency of event id is still increasing. 

We can fix this with certain "buffer" techniques, buy storing output event and observables in a buffer and write only the event with closest event id. This may slow down the speed.

**Comment by jgalan** [comment]
What are the consequences of this disorder?

**Comment by lobis** [comment]
> What are the consequences of this disorder?

I think this is only problematic if the user is not aware of it. One consequence that comes to mind is that for testing purposes, if we are comparing a known result file with a new one to verify the process still produces the same output, we may get a false negative, if we're just doing a diff.

**Comment by jgalan** [comment]
> 
> But I think storing them in order shouldn't impact performance. We could just apply a TTree sorting algorithm at the end of the analysis right? This should take little to no time to execute.


Maybe, but we need to recreate the `TTree` I believe, create an input-output tree scheme.

Another option when working with `threads` would be that if event `N+x` has been already processed, wait to do the fill when all lower event IDs have been processed, hoping that a specific event ID will not produce a specific bottleneck. I.e. all events take a similar time to finish. If event N+x takes very long time, the next N+x+threads events will be already processed and waiting for N+x to be filled.

A vector at `TRestThreads` or `TRestProcesser` could keep a list of ids being processed. When the fill is done, then it will pop-out the corresponding id and continue with the next one. The filling will wait till the id is trying to fill is the lowest event id found in the vector.

**Comment by nkx111** [comment]
I have implemented this feature on a testing branch(https://github.com/rest-for-physics/framework/tree/test_outeve_reorder). By executing with 4 threads and 200 event, we can see the output events are successfully re-ordered

before: 
```
root [0] AnalysisTree->Scan("eventID")
************************
*    Row   *   eventID *
************************
*        0 *         0 *
*        1 *         2 *
*        2 *         3 *
*        3 *         1 *
*        4 *         5 *
*        5 *         7 *
*        6 *         4 *
*        7 *         8 *
*        8 *        10 *
*        9 *         6 *
*       10 *        13 *
*       11 *        11 *
*       12 *         9 *
*       13 *        14 *
*       14 *        15 *
*       15 *        12 *
*       16 *        17 *
```

after:
```
root [0] AnalysisTree->Scan("eventID")
************************
*    Row   *   eventID *
************************
*        0 *         0 *
*        1 *         1 *
*        2 *         2 *
*        3 *         3 *
*        4 *         4 *
*        5 *         5 *
*        6 *         6 *
*        7 *         7 *
*        8 *         8 *
*        9 *         9 *
*       10 *        10 *
*       11 *        11 *
*       12 *        12 *
*       13 *        13 *
*       14 *        14 *
*       15 *        15 *
*       16 *        16 *
```
