### ISSUE TITLE
Not loading all macros

### ISSUE THREAD

**Issue by DavidDiezIb** [rest-for-physics/framework#282]
When I try to load macros it only finds those that are directly inside macros/ directory, not those in subdirectories, for example macros/geant4/

I'm using
 Commit  : d305f755 (2022-08-26 13:56:03 +0200)
 Branch/Version : master/v2.3.12
 Compilation date : 2022-08-29 01:13

![imagen](https://user-images.githubusercontent.com/77273709/187190609-04397ba2-4d68-4b2e-b18b-8ad48930e1e9.png)

**Comment by lobis** [comment]
Looks like `restRoot` only loads macros from the `macros` directory, so probably the issue is that these macros are not being copied to the directory on install

```
if (loadMacros) {
    if (!silent) printf("= Loading macros ...\n");
    auto filesMatchingPattern = TRestTools::GetFilesMatchingPattern(REST_PATH + "/macros/*REST_*.C");
    for (const auto& file : filesMatchingPattern) {
        if (file.find("swp") != string::npos || file.find("svn") != string::npos ||
            file.find("swo") != string::npos)
            continue;
        if (debug) printf("Loading macro : %s\n", file.c_str());

        gROOT->ProcessLine((".L " + file).c_str());
    }
}
```

**Comment by DavidDiezIb** [comment]
Well, they are but inside other subdirectories:
![imagen](https://user-images.githubusercontent.com/77273709/187192284-f4a172a3-cbee-4bab-a133-dda1c81326dd.png)
