### ISSUE TITLE
Recover PR #244 without breaking rawlib pipeline

### ISSUE THREAD

**Issue by jgalan** [rest-for-physics/framework#287]
I had to remove PR#244 in order to fix the pipeline at rawlib. I am not sure what is causing the problems, but it needs to be reviewed and identified the problem.

It would be good that the GitHub actions trigger the rawlib validation pipeline, if it does not do it already.

**Comment by nkx111** [comment]
fixed in https://github.com/rest-for-physics/framework/pull/289
