### ISSUE TITLE
The browser shows duplicated entries

### ISSUE THREAD

**Issue by jgalan** [rest-for-physics/framework#338]
It would  be great if we could solve the problem of replicated objects in a TBrowser. I usually don't use the Browser and then this problem does not appear often to me, anyway it is not good when this happens.

I produced this image using `pipeline/trex`.

<img width="319" alt="Screenshot 2022-11-28 at 11 44 33" src="https://user-images.githubusercontent.com/12447509/204258923-96f2ec56-22e9-4125-b497-20c747a13a6a.png">

**Comment by jgalan** [comment]
@nkx I thought it could be related with the *test run* that is done at `TRestProcessRunner`?

**Comment by lobis** [comment]
Perhaps this can be solved by using `kOverwrite` as an option in the appropiate instances of `TObject::Write`. I remember having to do this to avoid having "duplicated" (not really duplicated) entries.

**Comment by juanangp** [comment]
> Perhaps this can be solved by using `kOverwrite` as an option in the appropiate instances of `TObject::Write`. I remember having to do this to avoid having "duplicated" (not really duplicated) entries.

Kind of remember you point to me to this issue in `restG4` migth be the  `kOverwrite` option

**Comment by jgalan** [comment]
My guess is that the pointers are different for each copy.

**Comment by juanangp** [comment]
Did you try to use  `kWriteDelete` instead of `kOverwrite`? https://root.cern.ch/doc/master/classTObject.html

**Comment by jgalan** [comment]
Just tried adding that option to every `Write` call at [`TRestRawSignalChannelA](https://github.com/rest-for-physics/rawlib/blob/master/src/TRestRawSignalChannelActivityProcess.cxx)

and the result does not change much.

<img width="204" alt="Screenshot 2022-11-29 at 19 44 35" src="https://user-images.githubusercontent.com/12447509/204619013-96705461-1f85-4904-bfe1-ef1df06b03e9.png">

No beers yet
