### ISSUE TITLE
Removing detectorlib dependencies inside rawlib

### ISSUE THREAD

**Issue by jgalan** [rest-for-physics/framework#384]
Please, be aware that I have removed detector lib dependencies that were found inside rawlib.

This might affect in future to event data processing in TREX or IAXO where we were using channel activity. Now detector readout channel activity should be done at the detectorlib stage (To be implemented)
https://github.com/rest-for-physics/detectorlib/pull/65

https://github.com/rest-for-physics/rawlib/pull/92

https://github.com/rest-for-physics/legacylib/pull/4

- [x] We need to implement a `TRestDetectorChannelActivityProcess` that generates the readout activity histograms that were previously produced at `TRestRawSignalChannelActivityProcess` (removed at https://github.com/rest-for-physics/rawlib/pull/92)

**Comment by cmargalejo** [comment]
I agree that removing the dependencies is good, but it was very useful to see the raw signal channel activity in a histogram with readout coordinates, as it is more informative in case there is noise in a particular region, etc. 

And maybe I'm missing something, but we already have `TRestDetectorSignalChannelActivityProcess`, which produces the histogram of signal events. However, you write we should implement `TRestDetectorChannelActivityProcess`. Wouldn't this be the same? 

Still, I think we should include somwhere the posibility of producing the histogram in readout coordinates not only of the signal events but also the raw signal events.

**Comment by DavidDiezIb** [comment]
I don't care about DetectorSignal or RawSignal as far as we can do the readout channel activity for all signals, not only those that satisfy whatever. So this should be done before any "good signal" identification. 

Precisely this good signal identification could be done in this process (I'm thinking on events with all signals, maybe we are interested on taking only "good signals" for the readout channel activity histogram). 

But is very useful to have the posibility of working wih the full signal and its position.

**Comment by jgalan** [comment]
> I agree that removing the dependencies is good, but it was very useful to see the raw signal channel activity in a histogram with readout coordinates, as it is more informative in case there is noise in a particular region, etc.

Ok, perhaps one way would be to simply add a decoding file to the Raw process as a text file so that the process just takes that to create the ordered raw activity map.

**Comment by jgalan** [comment]
> I agree that removing the dependencies is good, but it was very useful to see the raw signal channel activity in a histogram with readout coordinates, as it is more informative in case there is noise in a particular region, etc.
> 
> And maybe I'm missing something, but we already have `TRestDetectorSignalChannelActivityProcess`, which produces the histogram of signal events. However, you write we should implement `TRestDetectorChannelActivityProcess`. Wouldn't this be the same?
> 
> Still, I think we should include somwhere the posibility of producing the histogram in readout coordinates not only of the signal events but also the raw signal events.

Right, I didn't see that before, it already exists!

**Comment by jgalan** [comment]
> I don't care about DetectorSignal or RawSignal as far as we can do the readout channel activity for all signals, not only those that satisfy whatever. So this should be done before any "good signal" identification.

You could still require that the raw to detector signal conversion includes all the channels.

But the solution with the text decoding file I proposed before would be a solution.

**Comment by jgalan** [comment]
Also, the readout channel activity could be done in the analysis stage. I find it not very clean that we are producing those histograms using the processing chain. 

There will be enough information at the analysis tree, at the `std::map` observables to generate those histograms. Those, one could have a little macro that produces those histograms with more flexibility. I don't like the idea that those histograms are written in the data processing files. But, it was an easy solution at the very beginning.

E.g. one should be able to produce the activity histograms using a macro that has access to the `TRestDetectorReadout` and the analysis tree.

```
Observable : rawAna_pointsoverthres_map                       Value : {[6:52],[7:51],[9:0],[228:0],[230:0],[234:47],[350:0],[351
Observable : rawAna_risetime_map                              Value : {[6:20],[7:17],[9:0],[228:0],[230:0],[234:18],[350:0],[351
Observable : rawAna_peak_time_map                             Value : {[6:206],[7:205],[9:203],[228:205],[230:205],[234:204],[35
Observable : rawAna_baseline_map                              Value : {[6:290.992],[7:279.969],[9:284.431],[228:283.092],[230:28
Observable : rawAna_baselinesigma_map                         Value : {[6:8.1783],[7:11.0766],[9:17.4223],[228:20.3282],[230:17.
Observable : rawAna_max_amplitude_map                         Value : {[6:223.008],[7:174.031],[9:237.569],[228:204.908],[230:20
Observable : rawAna_thr_integral_map                          Value : {[6:7200.4],[7:5823.57],[9:0],[228:0],[230:0],[234:5194.88
```

**Comment by DavidDiezIb** [comment]
> Thus, one could have a little macro that produces those histograms with more flexibility.

Actually, this is what I did when I was cheking the decoding files, I have a macro already to read RawSignals and the readout file.

**Comment by jgalan** [comment]
So just contribute it as something as `REST_Detector_SignalActivityMaps` placed at the detectorlib since it will access the detector readout and the analysis tree observables produced by the rawAna.

**Comment by jgalan** [comment]
> > Thus, one could have a little macro that produces those histograms with more flexibility.
> 
> Actually, this is what I did when I was checking the decoding files, I have a macro already to read RawSignals and the readout file.

If the macro reads `TRestRawSignal`s and accesses the `TRestDetectorReadout`, then the macro should be placed at the connectors lib, also possible.

**Comment by DavidDiezIb** [comment]
Maybe something like this [ac0a561f8174df943dbe6912f3cd3984b9f911a9](https://github.com/rest-for-physics/connectorslib/commit/ac0a561f8174df943dbe6912f3cd3984b9f911a9)

It is a macro that generates two plots, readout channel activity in X and Y. It extracts the paremeters (number of channels, size of readout plane, signal ID conversion) from readout file.

**Comment by jgalan** [comment]
Perfect, then just create a PR
