### ISSUE TITLE
Properly uninstalling the files from previous installation

### ISSUE THREAD

**Issue by jgalan** [rest-for-physics/framework#395]
After some discussions with @lobis and @juanangp we should try to avoid to completely remove the previous installation directory, in favor of using `install_manifest.txt` to remove the previous installation files during the `make install`.

https://gitlab.kitware.com/cmake/community/-/wikis/FAQ#can-i-do-make-uninstall-with-cmake

Just wondering, there is any chance that zombie files keep residing after removing `install_manifest.txt` files?

This is linked to PR #394

**Comment by juanangp** [comment]
> Just wondering, there is any chance that zombie files keep residing after removing `install_manifest.txt` files?

It seems that the pcm files are still there
