### ISSUE TITLE
Replace library version system.

### ISSUE THREAD

**Issue by jgalan** [rest-for-physics/framework#449]
Up to now we update the library version inside `CMakeLists.txt` manually. I think a more efficienct way would be to read the latest git tag name inside the `cmake` system so that just tagging is enough to define a human version.

What do you think?

the cmake variable `LIBRARY_VERSION` inside cmake could be simply filled by a call to a `git` command that returns the latest tag.

**Comment by jgalan** [comment]
I have already implemented a preliminary here: https://github.com/rest-for-physics/rawlib/pull/110/commits/608d4f3272650119199985eaf3cd197e284d58e5 and here https://github.com/rest-for-physics/rawlib/pull/110

**Comment by lobis** [comment]
I was already working on this also
