### ISSUE TITLE
Recovering event pointer when using `restRoot file.root`

### ISSUE THREAD

**Issue by jgalan** [rest-for-physics/framework#452]
Before #441 we could access the event pointer stored inside the ROOT file. I.e. `TRestGeant4Event`, `TRestRawSignalEvent`, ... depending on which event was available.

Now we recover a pointer to the event tree. 

Could we recover back the old behaviour? For me it was interesting to have ready access to the event as `ev0`.

Also, why not use the pointer instance name as `md_mdName`? instead of `metadata0["restG4 run"]` which we get right now?

I also think the `0` could disappear now from instance names.

<img width="838" alt="Screenshot 2023-06-20 at 18 23 38" src="https://github.com/rest-for-physics/framework/assets/12447509/162d67d7-a025-4b80-ad6b-8213258a604f">

**Comment by juanangp** [comment]
> Could we recover back the old behaviour? For me it was interesting to have ready access to the event as `ev0`.

Now the input `TRestEvent` is accessible via `ev`
> Also, why not use the pointer instance name as `md_mdName`? instead of `metadata0["restG4 run"]` which we get right now?

Now we have a map of `TRestMetadata` pointers, that's why we have the `metadata["metaName"]`, it is not possible to define a variable with a particular name pattern. This was done previously with `gROOT->ProcessLine(...);` that I think we should try to avoid.

> I also think the `0` could disappear now from instance names.

Done

**Comment by jgalan** [comment]
However, the interpreter seems to do not like it. See issue #450

**Comment by juanangp** [comment]
> However, the interpreter seems to do not like it. See issue #450

Weel, it is not possible to attach an `std::map<std::string, TRestMetadata*>` as  `TRestMetadata*` so the root interpreter gets confused. I have added a solution on #453 by using `gROOT->ProcessLine`. Please close the other issue...
