### ISSUE TITLE
CMake add an option to enable all libraries

### ISSUE THREAD

**Issue by jgalan** [rest-for-physics/framework#5]
We need to upgrade the cmake library system so that we are able to enable all libraries but still remove one library from the list.

For example, lets imagine I want to add all libraries for compilation except for the `geant4` library. Then, I would be able to do:

```
cmake --all-libs -DRESTLIB_GEANT4=OFF ../
```

or

```
cmake -DREST_ALL_LIBS=ON -DRESTLIB_GEANT4=OFF ../
```

When using such a `cmake` construction, the `REST_ALL_LIBS=ON` or `--all-libs` definitions should enable all the list of variables that start by `RESTLIB_`.

I found a solution to this problem here:
https://gitlab.kitware.com/cmake/community/-/wikis/doc/tutorials/SettingVariableGroups

However, I was not lucky on a first try.

There is a problem with `REST_ALL_LIBS` being cached. And even if I do:

```
cmake -DREST_ALL_LIBS=ON ../
```

and then

```
cmake -DRESTLIB_GEANT4=OFF ../
```

The second `cmake` execution will have no effect, since `REST_ALL_LIBS` will still be ON.

**Comment by nkx111** [comment]
The variable `REST_ALL_LIBS` is implemented now to turn off all the libraries and packages that not specified off. For example `cmake -DREST_ALL_LIBS=ON -DRESTLIB_GEANT4=OFF ../`. The problem that `REST_ALL_LIBS` is being cached is still there. But I don't think it is a problem. This is the logic of cmake: it always caches the variable once appeared. We re-run cmake and the cached variable still takes effect. We shall assume our user knows. On the other hand, if we make `REST_ALL_LIBS` uncached, this is an abnormal behavior, we shall write it in the readme.

**Comment by jgalan** [comment]
Ok, I believe with the new updates it is ok. I think it was perfect, at least the following succession of commands did what I expected:

```
cmake -DREST_ALL_LIBS=ON -DRESTLIB_GEANT4=OFF -DREST_G4=OFF -DRESTLIB_AXION=OFF ../
```
and
```
cmake -DRESTLIB_AXION=ON ../
```
