### ISSUE TITLE
Compilation issues inside TRestDataSetGainMap related to `RDataFrame::Redefine` not found.

### ISSUE THREAD

**Issue by jgalan** [rest-for-physics/framework#505]
@jovoy just reported a problem of compilation related to the `TRestDataSetGainMap`.

```
error: 'class ROOT::RDF::RInterface<ROOT::Detail::RDF::RNodeBase, void>' has no member named 'Redefine'; did you mean 'Define'? in the TRestDataSetGainMap.cxx
```

This is probably related to the ROOT version?

**Comment by juanangp** [comment]
> This is probably related to the ROOT version?

I think so, we are using root version 6.28 in sultan and as far as I know we don't have any compilation issue.

**Comment by AlvaroEzq** [comment]
> > This is probably related to the ROOT version?
> 
> I think so, we are using root version 6.28 in sultan and as far as I know we don't have any compilation issue.

Yes, RDataFrame::Redefine was added in root version [6.26](https://root.cern/doc/v626/release-notes.html#release-6.2600)

**Comment by jgalan** [comment]
I guess @jovoy got an older version?

**Comment by jovoy** [comment]
No, I've tried 28.02, 28.10 and 30.02. Is there a way to check which ROOT version REST thinks I'm using?

**Comment by jovoy** [comment]
Thank you, that was it!
