### ISSUE TITLE
clean-state.sh improve output. Make it more user friendly.

### ISSUE THREAD

**Issue by jgalan** [rest-for-physics/framework#8]
When we execute this script, if there are submodules where we have no access, it will output errors when trying to pull from those non-authorised repositories.

Even if we have access to all submodules this script will produce a lot of info. This script could be more sophisticated and control the output that throws on screen by using something similar to `pull-submodules.py` script.

**Comment by nkx111** [comment]
Perhaps we can remove this script now and use single `pull-submodules.py`?

**Comment by jgalan** [comment]
Yes, it is possible to remove it. I just thought it would be good to have a straight forward command, without arguments that cleans the repository. Of course, we can do that with `pull-submodules.py`.

But I would be good to add a `pull-submodules.py --help` to explain the different usage scenarios.
