### ISSUE TITLE
TRestAnalysisPlot. A problem appears now when trying to save with absolute path

### ISSUE THREAD

**Issue by jgalan** [rest-for-physics/framework#81]
It seems that some problem appears when trying to save to a full path in `TRestAnalysisPlot`.

Probably the problem was introduced at the following commit, when adding the `GetDataPath` at line 167.

https://gitlab.cern.ch/rest-for-physics/framework/-/commit/316a3cfd957a6acd71c110ae88b2e485a21ca483

Solution could be checking if the first character at the given user value is `/`.

**Comment by jgalan** [comment]
I also liked that the default would be writting at `/tmp/restplot.pdf`

**Comment by nkx111** [comment]
It this issue fixed in this PR?

https://github.com/rest-for-physics/framework/pull/99

**Comment by jgalan** [comment]
Yes, I believe it is solved. It corresponds to commit 9e97a22. So I will just close, if that didn't cause any unexpected issues I will just close this one.
