### ISSUE TITLE
dataURL is being used at user space, but if modified is not updated.

### ISSUE THREAD

**Issue by jgalan** [rest-for-physics/framework#9]
This issue was described on the forum post at:

http://ezpc10.unizar.es/t/updating-dataurl-at-user-home-space/428

An straight forward solution would be to avoid using `dataURL` at user space, and use it the one directly at the install path. But it might be the case that the user wants to add personalised entries?

**Comment by nkx111** [comment]
Now we discard the one on user space. We only use the one in $REST_PATH/data/dataURL
