### ISSUE TITLE
cmake system sometimes does not add geant4.sh to thisREST.sh

### ISSUE THREAD

**Issue by jgalan** [rest-for-physics/framework#92]
It has been observed that sometimes the cmake system identifies a Geant4 installation, but it does not add properly the `geant4.sh` script to be loaded at `thisREST.sh`.

This is probably linked with compiling REST without loading Geant4 using previously `source /../../geant4.sh` but cmake system properly identifying a Geant4 installation and going all the way through without imposing the geant4 version at `thisREST.sh` script.

It would be good to fix this problem to avoid problems connected with the following forum topic:

http://rest-forum.unizar.es/t/restg4-undefined-symbol-error-in-v2-3-8-official-release/499/2

**Comment by lobis** [comment]
@jgalan Is this still a problem? this should not happen at all I can take a look.

**Comment by lobis** [comment]
I will close this issue since its been inactive for a while, please reopen if this is still relevant.
